"""foundation storage"""
import sqlalchemy as sa
from alembic import op

revision = '0001_foundation'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harness_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('harness_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['harness_id'], ['harness_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint('revision >= 1'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'revision'),
    sa.UniqueConstraint('id', 'dataset_id')
    )
    op.create_table('source_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('sheet', sa.String(), nullable=False),
    sa.Column('physical_row', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint('physical_row >= 1'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'sheet', 'physical_row')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('mapping_id', sa.String(), nullable=False),
    sa.Column('harness_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('mapping_snapshot', sa.JSON(), nullable=False),
    sa.Column('harness_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('queued','running','completed','failed')"),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['harness_id'], ['harness_versions.id'], ),
    sa.ForeignKeyConstraint(['mapping_id', 'dataset_id'], ['mappings.id', 'mappings.dataset_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('job_rows',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lease_owner', sa.String(), nullable=True),
    sa.Column('lease_expires_at', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','completed','failed')"),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['source_rows.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'transaction_id')
    )
    op.create_table('model_attempts',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.CheckConstraint('number >= 1 AND number <= 2'),
    sa.ForeignKeyConstraint(['job_id', 'transaction_id'], ['job_rows.job_id', 'job_rows.transaction_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'transaction_id', 'number')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id', 'transaction_id'], ['job_rows.job_id', 'job_rows.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'transaction_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    op.drop_table('model_attempts')
    op.drop_table('job_rows')
    op.drop_table('jobs')
    op.drop_table('source_rows')
    op.drop_table('mappings')
    op.drop_table('evaluations')
    op.drop_table('harness_versions')
    op.drop_table('datasets')
    # ### end Alembic commands ###
